28/show chat
graasp/graasp-perform pull request #31
Opened 2021-10-08 12:12 UTC by Julien-Torrent

close #31 #17

2021-10-11 07:45 UTC, pyphilia requested changes
Thanks for this PR! I left some reviews to address.

2021-10-11 07:45 UTC, pyphilia commented on cypress/fixtures/useCases/staticElectricity.js
> +      settings:{}
Missing space.

2021-10-11 07:45 UTC, pyphilia commented on cypress/fixtures/useCases/staticElectricity.js
> +      settings:{}
Missing space.

2021-10-11 07:45 UTC, pyphilia commented on cypress/fixtures/useCases/staticElectricity.js
> +      settings:{}
Missing space.

2021-10-11 07:45 UTC, pyphilia commented on cypress/fixtures/useCases/staticElectricity.js
> +      settings:{}
Missing space.

2021-10-11 07:45 UTC, pyphilia commented on cypress/fixtures/useCases/staticElectricity.js
> +      settings:{}
Missing space.

2021-10-11 07:45 UTC, pyphilia commented on cypress/fixtures/useCases/staticElectricity.js
> +      settings:{}
Missing space. And all above.

2021-10-11 07:45 UTC, pyphilia commented on package.json
> +    "@material-ui/icons": "5.0.0-beta.4",
Did you really need to update the icons?

2021-10-11 07:45 UTC, pyphilia commented on src/components/common/Chatbox.js
> +        sendMessageBoxId="test"
Remove? Or factor out as a selector.

2021-10-11 07:45 UTC, pyphilia commented on src/components/common/Chatbox.js
> +        id="test"
Some as below.

2021-10-11 07:45 UTC, pyphilia commented on src/components/common/SideContent.js
> +const drawerWidth = 400;
Factor out in constants.

2021-10-11 07:45 UTC, pyphilia commented on src/components/common/SideContent.js
> +  const parentId = getDirectParentId(item.get('path')) || item.get('path');
Factor out in utils.

2021-10-11 07:45 UTC, pyphilia commented on src/components/common/SideContent.js
> +          aria-label="open drawer"
translate?

2021-10-11 07:45 UTC, pyphilia commented on src/components/common/SideContent.js
> +          aria-label={ isPinnedMenuOpen ? "Hide pinned items" : "Show pinned items"}
Translate.

2021-10-11 07:45 UTC, pyphilia commented on src/components/common/SideContent.js
> +      <Paper square>
What does `square` do?

2021-10-11 09:28 UTC, Julien-Torrent commented on src/components/common/SideContent.js
> +      <Paper square>
It removes round edges

2021-10-13 12:56 UTC, pyphilia requested changes
Thanks for the PR! I think we should be careful with `settings` and be sure it can work even if the data is undefined.

2021-10-13 12:56 UTC, pyphilia commented on src/components/common/SideContent.js
> +              isChatboxMenuOpen ? t('Hide Chat') : t('Hide Chat')
Double `Hide Chat`?

2021-10-13 12:56 UTC, pyphilia commented on src/components/common/SideContent.js
> +        {item.get('settings').showChatbox ? (
I think it is not worthless to have some protection of undefined settings ->  add a `?`

2021-10-13 12:56 UTC, pyphilia commented on src/components/common/SideContent.js
> +        ) : undefined}
It is better to use `null`. And actually I would factor out part of the component (especially those where you need `: null`) in a separate function and have something like: 
```
() => {
if(!showChat) return null

return (ccc)
}
```

2021-10-13 12:56 UTC, pyphilia commented on src/langs/fr.json
> +    "Hide Pinned Items": "Cacher les eléments épinglés"
`éléments`

2021-10-13 12:56 UTC, pyphilia commented on src/components/main/MainScreen.js
> +        <SideContent item={item}>{[content]}</SideContent>
I'm not sure it's good to override the usual type of children. Isn't it possible to use a component instead of an array?

2021-10-15 09:04 UTC, pyphilia approved these changes
Very nice, we're almost there. I left one last suggestion, and you can merge.

2021-10-15 09:04 UTC, pyphilia commented on src/components/common/SideContent.js
> +  const displayChatbox = () => {
If possible, I think it makes sense to create whole component for this/these components.

2021-10-21 08:18 UTC, merged