feat: add shortcut previous button and map button
graasp/graasp-perform pull request #716
Opened 2024-05-22 09:58 UTC by pyphilia

- map button to return to builder's map 
  - close #714 
- add shortcut from button **within player only** 
  - close #715 

<img width="943" alt="Screenshot 2024-05-22 at 11 56 02" src="https://github.com/graasp/graasp-player/assets/11229627/544ab5b9-6509-4af5-9ab3-661b3b939b3f">

2024-05-23 13:29 UTC, LinaYahya approved these changes

2024-05-24 09:16 UTC, spaenleh requested changes
Looks good, just a few nitpicks and a layout issue. Let me know if you have questions. 🎈

2024-05-24 09:16 UTC, spaenleh commented on cypress/e2e/shortcut.cy.ts
> +  it.only('Hacking from url with external url is safe', () => {
remove only ?

2024-05-24 09:16 UTC, spaenleh commented on package.json
> +    "@graasp/sdk": "github:graasp/graasp-sdk#qs-for-host-manager",
An sdk version has been created, you can update.

2024-05-24 09:16 UTC, spaenleh commented on src/config/selectors.ts
> +export const ITEM_MAP_BUTTON_ID = 'item-map-button';
use the same standard ? 😅

2024-05-24 09:16 UTC, spaenleh commented on src/langs/fr.json
> +  "FROM_SHORTCUT_BUTTON_TEXT": "Retourner sur {{name}}"
Not sure...
```suggestion
  "FROM_SHORTCUT_BUTTON_TEXT": "Retourner à {{name}}"
```

2024-05-24 09:16 UTC, spaenleh commented on src/modules/item/Item.tsx
> +  searchParams.set('fromName', item.name);
Does this modify the params of the current page ? Should we make a copy ?

2024-05-24 09:16 UTC, spaenleh commented on src/modules/item/SectionHeader.tsx
> +          </Stack>
I think you did not mean to change this code. It broke the header:
Before:
<img width="652" alt="Screenshot 2024-05-24 at 11 10 49" src="https://github.com/graasp/graasp-player/assets/39373170/6a4631de-d073-49b4-9ff1-189ff4f48fbf">
Now: 
<img width="580" alt="Screenshot 2024-05-24 at 11 10 09" src="https://github.com/graasp/graasp-player/assets/39373170/15dd4690-9112-4944-b32e-d2e2efa0df76">

2024-05-24 09:16 UTC, spaenleh commented on src/modules/navigationIsland/CustomButtons.tsx
> +  },
Nice addition

2024-05-24 09:16 UTC, spaenleh commented on src/modules/item/FromShortcutButton.tsx
> +          to={fromUrl}
Does this maintain the existing query params ? like fullscreen etc ?

2024-05-24 09:16 UTC, spaenleh commented on src/modules/navigationIsland/GeolocationButton.tsx
> +      <ToolButton key="chatButton" disabled={isDisabled} aria-label={tooltip}>
```suggestion
      <ToolButton key="mapButton" disabled={isDisabled} aria-label={tooltip}>
```

2024-05-24 09:25 UTC, ReidyT reviewed
I didn't have checked the code yet, but it is wanted to have the button in orange ? Should we use graasp's primary colour instead, so that the button integrates in better with the rest of the design?

2024-05-28 14:33 UTC, spaenleh approved these changes
Looks good !

2024-05-28 15:12 UTC, merged